
```mermaid
graph TD
    A[Developer PR] --> B[GitHub Actions]
    B --> C[Static Checks:<br/>tfsec/Checkov/OPA]
    C --> D[Terraform Plan - Test]
    D --> E[Apply - Test]
    E --> F[Plan - Live]
    F -->|Manual Approval| G[Apply - Live]
    G --> H[AWS: VPC/EC2/SG/NAT]
    H --> I[CloudTrail/Config/GuardDuty/SecurityHub]
    I --> J[SNS Alerts]
    K[EventBridge] --> L[Lambda Auto-Remediation]
    L --> H
    
    subgraph State
        M[S3 Terraform State]:::state
        N[DynamoDB Locks]:::state
        M --> N
    end
    
    classDef state fill:#eef,stroke:#99f,stroke-width:1px
```
