```mermaid
graph TD
  A[Developer PR] --> B[GitHub Actions]
  B --> C[Static Checks: tfsec / Checkov / OPA]
  C --> D[Terraform Plan (Test)]
  D --> E[Apply (Test)]
  E --> F[Terraform Plan (Live)]
  F --> G[Manual Approval]
  G --> H[Apply (Live)]

  H --> I[AWS Resources: VPC / EC2 / SG / NAT]
  I --> J[CloudTrail / Config / GuardDuty / SecurityHub]
  J --> K[SNS Alerts]

  K --> L[EventBridge Rule]
  L --> M[Lambda Auto-Remediation]
  M --> I

  subgraph State_Management
    N[S3 Terraform State]
    O[DynamoDB State Lock]
    N --> O
  end
```
